//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotMvc.Models.EntitiyFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOGRETMENLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLOGRETMENLER()
        {
            this.TBLDERS = new HashSet<TBLDERS>();
        }
    
        public byte OGRETMENID { get; set; }
        public string OGRETMENAD { get; set; }
        public string OGRETMENSOYAD { get; set; }
        public string OGRETMENBRANS { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDERS> TBLDERS { get; set; }
    }
}
